site_name: CGILABS Docs
site_url: https://cgilabs.github.io/


theme:
  name: null
  custom_dir: theme/mkdocs-gitbook-theme/mkdocs_gitbook

nav:
  - Home: index.md
  - Unreal:
      - Week 1: unreal/week01.md
      - Week 2: unreal/week02.md

plugins:
  - search
  - revealjs:
      theme: black
      transition: slide