site_name: ArtCenter
site_url: https://cgilabs.github.io/

theme:
  name: material
  custom_dir: overrides
  language: ko
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: white
      accent: blue

plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Creator:
      - Creator: creator/index.md
      - 3D 모델링 준비하기:
          - 모델링 준비하기 - 의상: creator/modeling-ready-cloth.md
          - 모델링 준비하기 - 신발: creator/modeling-ready-shoes.md
          - 모델링 준비하기 - 헤어, 헤드웨어: creator/modeling-ready-hair.md
      - 3D 모델링하기:
          - 3D 모델링하기 - 의상: creator/modeling-cloth.md
          - 3D 모델링하기 - 헤어: creator/modeling-hair.md
      - 3D 맵핑하기: creator/mapping.md
      - 3D 리깅하기: creator/rigging.md
      - Unity Engine: creator/unity.md
      - 3D 컨버팅&내보내기: creator/export.md

  - Icon:
      - 썸네일 가이드라인: icon/thumbnail-guide.md

  - Modeling: modeling/index.md
  - Page: page/index.md
  - Page 1: page/page1.md